import {
  GraduationCap, Home, IdCard, BarChart3, CalendarDays, Star,
  CalendarCheck, CreditCard, UserCircle, Link as LinkIcon, Lock,
  KeyRound, Copy, Check, Settings, LogOut, Search, Bell, ChevronRight,
  ChevronDown, ChevronUp, ChevronsUpDown, Menu, QrCode, Download,
  Table, Pencil, Trash2, Info, Gavel, Headset, Phone, Mail, Landmark,
  Fingerprint, MapPin, Save, AlertCircle, CheckCircle, Construction,
  ShieldCheck, LayoutDashboard, Users, BookOpen, CalendarRange,
  MessageSquare, UserPlus, User, ArrowRight, FileEdit, Calendar,
  X, AlertTriangle, TrendingUp, Hourglass, Globe, Eye, EyeOff,
  Plus, CircleDot, Circle, Clock, Building, DoorOpen, BookMarked,
  Receipt, History, Award, FileText, Send, ChevronLeft,
  MoreVertical, Filter, RefreshCw, Loader2, ExternalLink, Flag,
  Languages, Hash, ListOrdered, ToggleLeft, ToggleRight, Minus,
  UserCog, Database, MonitorDot, PersonStanding, Newspaper,
  CalendarClock, Layers, ClipboardList, PanelLeft, BarChart,
  Umbrella, Zap, MessageCircle, Quote, LineChart,
  Upload, Presentation, UserCheck, ClipboardCheck, HelpCircle,
  ArrowLeft, Sparkles, Cake, Calculator, ListChecks, Sigma,
  Network, Building2, Map as MapIcon, HandHeart
} from 'lucide-react';

/** Map every icon name string used in the app (nav, DB, etc.) to a Lucide component */
const ICON_MAP = {
  // Navigation / brand
  school: GraduationCap,
  home: Home,
  badge: IdCard,
  bar_chart: BarChart3,
  grade: BarChart3,
  analytics: BarChart3,
  calendar_month: CalendarDays,
  rate_review: Star,
  event_available: CalendarCheck,
  payments: CreditCard,
  credit_card: CreditCard,
  account_circle: UserCircle,
  link: LinkIcon,
  add_link: LinkIcon,
  lock: Lock,
  key: KeyRound,
  content_copy: Copy,
  check: Check,
  check_circle: CheckCircle,
  settings: Settings,
  logout: LogOut,
  search: Search,
  notifications: Bell,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  unfold_more: ChevronsUpDown,
  menu: Menu,
  qr_code_2: QrCode,
  download: Download,
  table_chart: Table,
  edit: Pencil,
  edit_note: FileEdit,
  delete: Trash2,
  info: Info,
  gavel: Gavel,
  contact_support: Headset,
  contact_phone: Phone,
  phone: Phone,
  mail: Mail,
  account_balance: Landmark,
  fingerprint: Fingerprint,
  home_pin: MapPin,
  location_on: MapPin,
  save: Save,
  error: AlertCircle,
  construction: Construction,
  admin_panel_settings: ShieldCheck,
  dashboard: LayoutDashboard,
  group: Users,
  groups: Users,
  menu_book: BookOpen,
  calendar_view_week: CalendarRange,
  reviews: MessageSquare,
  group_add: UserPlus,
  person: User,
  person_add: UserPlus,
  arrow_forward: ArrowRight,
  event: Calendar,
  event_note: Calendar,
  close: X,
  warning: AlertTriangle,
  trending_up: TrendingUp,
  hourglass_empty: Hourglass,
  language: Globe,
  visibility: Eye,
  visibility_off: EyeOff,
  add: Plus,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  schedule: Clock,
  access_time: Clock,
  apartment: Building,
  meeting_room: DoorOpen,
  assignment: ClipboardList,
  receipt_long: Receipt,
  history: History,
  verified_user: Award,
  description: FileText,
  send: Send,
  more_vert: MoreVertical,
  filter_list: Filter,
  refresh: RefreshCw,
  progress_activity: Loader2,
  open_in_new: ExternalLink,
  flag: Flag,
  translate: Languages,
  tag: Hash,
  format_list_numbered: ListOrdered,
  toggle_on: ToggleRight,
  toggle_off: ToggleLeft,
  remove: Minus,
  manage_accounts: UserCog,
  database: Database,
  monitoring: MonitorDot,
  tune: Settings,
  security: ShieldCheck,
  backup: Database,
  calendar_today: CalendarDays,
  pending_actions: Clock,
  star: Star,
  forum: MessageSquare,
  bar_chart_4_bars: BarChart,
  edit_calendar: CalendarClock,
  layers: Layers,
  id_card: IdCard,
  newspaper: Newspaper,
  panel_left: PanelLeft,
  workspace_premium: Award,
  military_tech: Award,
  beach_access: Umbrella,
  bolt: Zap,
  comment: MessageCircle,
  format_quote: Quote,
  forward_to_inbox: Send,
  insights: LineChart,
  upload_file: Upload,
  co_present: Presentation,
  how_to_reg: UserCheck,
  grading: ClipboardCheck,
  help: HelpCircle,
  // Documents, grading, generator, identity (features #1/#2/#3/#4)
  arrow_back: ArrowLeft,
  picture_as_pdf: FileText,
  volunteer_activism: HandHeart,
  cake: Cake,
  location_city: Building2,
  map: MapIcon,
  functions: Sigma,
  calculate: Calculator,
  checklist: ListChecks,
  task_alt: CheckCircle,
  sync: RefreshCw,
  preview: Eye,
  auto_awesome: Sparkles,
  hub: Network,
  category: Layers,
  stairs: Layers,
};

/**
 * Render a Lucide icon by its Material-Symbols-style name.
 * Falls back to a small "?" circle for unknown names.
 *
 * @param {{ name: string, size?: number, className?: string, strokeWidth?: number }} props
 */
export default function Icon({ name, size = 20, className = '', strokeWidth = 2, ...rest }) {
  const Component = ICON_MAP[name];
  if (!Component) {
    // Fallback – render the name as tiny text so we can spot unmapped icons easily
    return (
      <span
        className={`icon-fallback ${className}`}
        style={{ width: size, height: size, fontSize: size * 0.5 }}
        title={name}
        {...rest}
      >
        ?
      </span>
    );
  }
  return <Component size={size} strokeWidth={strokeWidth} className={`icon ${className}`} {...rest} />;
}

/** Curated list of icons suitable for the admin "Useful Links" icon picker */
export const LINK_ICON_OPTIONS = [
  { name: 'link', label: 'Link' },
  { name: 'info', label: 'Info' },
  { name: 'school', label: 'Universitate' },
  { name: 'gavel', label: 'Regulament' },
  { name: 'calendar_month', label: 'Calendar' },
  { name: 'contact_support', label: 'Suport' },
  { name: 'menu_book', label: 'Carte' },
  { name: 'description', label: 'Document' },
  { name: 'mail', label: 'Email' },
  { name: 'phone', label: 'Telefon' },
  { name: 'home', label: 'Acasă' },
  { name: 'download', label: 'Descarcă' },
  { name: 'open_in_new', label: 'Link extern' },
  { name: 'star', label: 'Stea' },
  { name: 'flag', label: 'Flag' },
  { name: 'warning', label: 'Avertizare' },
  { name: 'check_circle', label: 'Confirmat' },
  { name: 'settings', label: 'Setări' },
  { name: 'account_balance', label: 'Bancă' },
  { name: 'receipt_long', label: 'Chitanță' },
  { name: 'history', label: 'Istoric' },
  { name: 'newspaper', label: 'Știri' },
  { name: 'credit_card', label: 'Card' },
  { name: 'assignment', label: 'Formular' },
  { name: 'bar_chart', label: 'Grafic' },
  { name: 'error', label: 'Bug / Eroare' },
  { name: 'send', label: 'Trimite' },
  { name: 'layers', label: 'Straturi' },
];
